sudo: false
language: node_js
addons:
  postgresql: '9.4'
cache:
  directories:
    - node_modules
node_js:
  - '14'
before_script:
  - npm prune
  - typings install
script:
  - gulp
  - cd integration-test && ./run.sh
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
